### ISSUE TITLE
Comparing Int and Uint

### ISSUE THREAD

**Issue by sashmackinnon** [nitrobin/protohx#1]
In flash, you get the error:

> haxe: Comparison of Int and UInt might lead to unexpected results

when trying to perform the operation

> var tag:PT_UInt = protohx.ReadUtils.read__TYPE_UINT32(input);
>             switch (tag >> 3) {

tag >> 3 is causing the problem

**Comment by nitrobin** [comment]
Which version of haxe and protohx you use? This should work with haxe 3.1.3 and protohx 0.4.1.

**Comment by sashmackinnon** [comment]
Hey! 

I’m using 3.1.3 and 0.4.1.

It seems to only break when compiling for flash.

**Comment by nitrobin** [comment]
Hello! :) 
Strange.. Can you provide part of your *.proto file with problem 'message'?

There is simple test
https://github.com/nitrobin/protohx/blob/master/samples/01-core/build-flash.hxml
$(haxelib)/protohx/0,4,1/samples/01-core/build-flash.hxml

On my machine this test is ok. Test has same error? Do you use openfl(version)?

**Comment by sashmackinnon** [comment]
Sure!

I tried running the test, and got this error, am I running it incorrectly?

FAIL
sh: protoc: command not found
src/Main.hx:2: characters 7-15 : Class not found : test.Foo

Here is the proto:

message MMMonster {
    optional MMMonsterCard monsterCard = 1;
    repeated uint32 modifiersUsed = 2;
    repeated uint32 modifiers = 3; // list of scroll IDs
    repeated uint32 ownedSkills = 4; // list of owned skills
    repeated uint32 equippedGear = 5; // list of equipped gear ids
}

The problem is it compares uint32 to a regular int. Here is the full function. It breaks when comparing ‘tag’ to an int.

override public function readFromSlice(input:PT_InputStream, bytesAfterSlice:PT_UInt):Void {
        var monsterCard__count:PT_UInt = 0;
        while (hasBytes(input, bytesAfterSlice)) {
            var tag = Std.int(protohx.ReadUtils.read__TYPE_UINT32(input));
            switch (tag >> 3) {
            case 1:
                if (monsterCard__count != 0) {
                    throw new PT_IOError('Bad data format: MMMonster.monsterCard cannot be set twice.');
                }
                ++monsterCard__count;
                this.monsterCard = new minomonsters.proto.frosty.MMMonsterCard();
                protohx.ReadUtils.read__TYPE_MESSAGE(input, this.monsterCard);
            case 2:
                if(this.modifiersUsed == null) {
                    this.modifiersUsed = [];
                }
                if ((tag & 7) == Std.int(protohx.WireType.LENGTH_DELIMITED)) {
                    protohx.ReadUtils.readPackedRepeated(input, protohx.ReadUtils.read__TYPE_UINT32, this.modifiersUsed);
                } else              {
                    this.modifiersUsed.push(cast protohx.ReadUtils.read__TYPE_UINT32(input));
                }
            case 3:
                if(this.modifiers == null) {
                    this.modifiers = [];
                }
                if ((tag & 7) == Std.int(protohx.WireType.LENGTH_DELIMITED)) {
                    protohx.ReadUtils.readPackedRepeated(input, protohx.ReadUtils.read__TYPE_UINT32, this.modifiers);
                } else              {
                    this.modifiers.push(cast protohx.ReadUtils.read__TYPE_UINT32(input));
                }
            case 4:
                if(this.ownedSkills == null) {
                    this.ownedSkills = [];
                }
                if ((tag & 7) == Std.int(protohx.WireType.LENGTH_DELIMITED)) {
                    protohx.ReadUtils.readPackedRepeated(input, protohx.ReadUtils.read__TYPE_UINT32, this.ownedSkills);
                } else              {
                    this.ownedSkills.push(cast protohx.ReadUtils.read__TYPE_UINT32(input));
                }
            case 5:
                if(this.equippedGear == null) {
                    this.equippedGear = [];
                }
                if ((tag & 7) == Std.int(protohx.WireType.LENGTH_DELIMITED)) {
                    protohx.ReadUtils.readPackedRepeated(input, protohx.ReadUtils.read__TYPE_UINT32, this.equippedGear);
                } else              {
                    this.equippedGear.push(cast protohx.ReadUtils.read__TYPE_UINT32(input));
                }
            default:
                super.readUnknown(input, tag);
            }
        }
    }
}

**Comment by nitrobin** [comment]
Seems you have old version protohx..

<pre>
message MMMonster {
    //optional MMMonsterCard monsterCard = 1;
    repeated uint32 modifiersUsed = 2;
    repeated uint32 modifiers = 3; // list of scroll IDs
    repeated uint32 ownedSkills = 4; // list of owned skills
    repeated uint32 equippedGear = 5; // list of equipped gear ids
}
</pre>

My version produce code (with cast to PT_UInt):

<pre>
    override public function readFromSlice(input:PT_InputStream, bytesAfterSlice:PT_UInt):Void {
        while (hasBytes(input, bytesAfterSlice)) {
            var tag:PT_UInt = protohx.ReadUtils.read__TYPE_UINT32(input);
            switch (tag >> 3) {
            case 2:
                if(this.modifiersUsed == null) {
                    this.modifiersUsed = [];
                }
                if (cast((tag & 7), PT_UInt) == protohx.WireType.LENGTH_DELIMITED) {
                    protohx.ReadUtils.readPackedRepeated(input, protohx.ReadUtils.read__TYPE_UINT32, this.modifiersUsed);
                } else              {
                    this.modifiersUsed.push(cast protohx.ReadUtils.read__TYPE_UINT32(input));
                }
</pre>

Try to remove protohx from haxelib and install again..

**Comment by nitrobin** [comment]
"protoc: command not found"  Strange.. :/ Like protoc is not installed.. 
How did you generate sources from your proto? You use Linux?
I upload test with pre-generated sources. https://docs.google.com/uc?id=0B9gz9RtNUdaZZmltVUdSRUR2WnM&export=download

**Comment by sashmackinnon** [comment]
Great I think we have resolved this.

I was running the protoc command on another machine, which is why it wasn’t installed.

We had updated to the latest haxelib on that machine, but it was still producing the uncasted code.

We discovered that was happening was because when you update the haxelib, it doesn’t make the plugin executable. So we were pointing to the wrong plugin (but the right haxelib… weird). Not sure if there is any way around this.

Its all working now. Thanks Eugene, I really appreciate your help!

**Comment by nitrobin** [comment]
You are welcome! :)
There is small hook for Linux https://github.com/nitrobin/protohx/blob/master/tools/run/src/Helpers.hx#L106
Which OS you use?
Thanks for feedback!

**Comment by sashmackinnon** [comment]
Cool! We are using OSX

**Comment by nitrobin** [comment]
Mac build fixed in master
