### ISSUE TITLE
Package Uint to Int errors (on flash compiles)

### ISSUE THREAD

**Issue by martinwells** [nitrobin/protohx#2]
The following proto:

message MMMonster {
    optional MMMonsterCard monsterCard = 1;
    repeated uint32 modifiersUsed = 2 [packed=true];
    repeated uint32 modifiers = 3 [packed=true]; // list of scroll IDs
    repeated uint32 equippedGear = 4 [packed=true]; // list of equipped gear ids
}

Generates (cut sample):

```
    if (this.modifiersUsed != null && this.modifiersUsed.length > 0) {
        protohx.WriteUtils.writeTag(output, protohx.WireType.LENGTH_DELIMITED, 2);
        protohx.WriteUtils.writePackedRepeated(output, protohx.WriteUtils.write__TYPE_UINT32, this.modifiersUsed);
```

Which is causing:

Warning:(107, 89) haxe: Array<protohx.PT_UInt> should be Array<protohx.PT_Int>
Warning:(107, 89) haxe: Type parameters are invariant
Warning:(107, 89) haxe: UInt should be protohx.PT_Int
Warning:(107, 89) haxe: UInt should be Int
Warning:(107, 89) haxe: For function argument 'value'

**Comment by nitrobin** [comment]
Oops.. "repeated uint32" produce invalid haxe code. 
Try use "int"or maybe patch WriteUtils.write__TYPE_UINT32 like this:
"public static function write__TYPE_UINT32(output:PT_OutputStream, value:PT_UInt):Void "

I will try fix it near time. Thanks for feedback!

**Comment by nitrobin** [comment]
Fixed
